### ISSUE TITLE
Compilation fails 

### ISSUE THREAD

**Issue by Redbinhoob** [secruul/SysExec#1]
Hello there i was trying to rebuild   this  using mingw      in codeblocks  i didnt modify the code    
but the output had the following error and build failed 

`||=== Build: Debug in fdesa (compiler: GNU GCC Compiler) ===|
C:\Users\TheOrangePIE\vmlogs\New folder\webdev\HttpServer.h|9|warning: ignoring #pragma comment  [-Wunknown-pragmas]|
C:\Users\TheOrangePIE\vmlogs\New folder\webdev\HttpServer.h|10|warning: ignoring #pragma comment  [-Wunknown-pragmas]|
C:\Users\TheOrangePIE\vmlogs\New folder\webdev\HttpServer.h|11|warning: ignoring #pragma comment  [-Wunknown-pragmas]|
C:\Users\TheOrangePIE\vmlogs\New folder\webdev\HttpServer.h|12|warning: ignoring #pragma comment  [-Wunknown-pragmas]|
C:\Users\TheOrangePIE\vmlogs\New folder\webdev\SmbConnection.h|26|warning: "STATUS_SUCCESS" redefined|
C:\Program Files (x86)\CodeBlocks\MinGW\include\subauth.h|12|note: this is the location of the previous definition|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|103|error: 'SEC_WCHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|106|error: 'SEC_CHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|109|error: 'SEC_WCHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|110|error: 'SEC_WCHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|116|error: 'SEC_CHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|117|error: 'SEC_CHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|127|error: 'SEC_WCHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|130|error: 'SEC_CHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|137|error: 'SEC_WCHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|138|error: 'SEC_WCHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|145|error: 'SEC_CHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|146|error: 'SEC_CHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|154|error: 'SEC_WCHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|157|error: 'SEC_CHAR' does not name a type|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|163|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|163|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|164|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|164|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|165|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|165|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|166|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|166|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|167|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|167|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|168|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|168|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|169|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|169|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|170|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|170|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|171|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|171|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|172|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|172|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|173|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|173|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|174|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|174|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|175|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|175|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|176|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|176|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|177|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|177|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|178|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|178|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|179|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|179|error: expected primary-expression before '__attribute__'|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|180|error: typedef 'SECURITY_STATUS' is initialized (use decltype instead)|
C:\Program Files (x86)\CodeBlocks\MinGW\include\sspi.h|180|error: expected primary-expression before '__attribute__'|
||More errors follow but not being shown.|
||Edit the max errors limit in compiler options...|
||=== Build failed: 50 error(s), 5 warning(s) (0 minute(s), 0 second(s)) ===|
`

using 64 bit  windows 10  system  
i didnt have sspi by default so had to download from mingw  project https://sourceforge.net/p/mingw/mingw-org-wsl/ci/e79d278f3d6410be6c2af76a388b7678dbb7ff47/tree/w32api/include/sspi.h?format=raw

**Comment by NotGlop** [comment]
Hello, you can safely remove the SSPI.h include since it is not used anymore in the source code.
I'll update the code accordingly.
